export const RESTORE_PASSWORD_HOURS_LIMIT = 24;
export const RESTORE_PASSWORD_LIMIT = 5;
export const RESTORATION_TOKEN_EXPIRE = 86400000;
export const EMAIL_TOKEN_EXPIRE = 86400000;
export const EMAIL_VERIFICATION_HOURS_LIMIT = 24;
export const EMAIL_VERIFICATION_LIMIT = 5;
export const ADDITIONAL_AUTHENTICATION_TOKEN_EXPIRE = 300000;
export const ADDITIONAL_AUTHENTICATION_CODE_LENGTH = 6;