export interface ICreateFilter {
    readonly ruleId: number,
    readonly name: string,
    readonly criticalLow: number,
    readonly lowMin: number,
    readonly lowMax: number,
    readonly subOptimalMin: number,
    readonly subOptimalMax: number,
    readonly optimalMin: number,
    readonly optimalMax: number,
    readonly supraOptimalMin: number,
    readonly supraOptimalMax: number,
    readonly HighMin: number,
    readonly HighMax: number,
    readonly criticalHigh: number,
    readonly recommendationsIsOn: boolean,
}