export const errorsExplanations = {
    'Broke in centrifuge': 'sample being damaged',
    'Cancelled': 'test being cancelled',
    'Clotted': 'test being clotted',
    'Clumped': 'clump of White Blood Cells (WBC) ',
    'Degenerated': 'degeneration of White Blood Cells (WBC)',
    'Delayed separation': 'delay in receiving sample',
    'Discarded': 'sample being thrown away',
    'Discarded in error': 'sample being thrown away in error',
    'EDTA contam': 'sample being contaminated',
    'FO contamination': 'sample being contaminated',
    'Empty tube': 'sample tube being empty',
    'Haemolysed': 'breakdown of Red Blood Cells (Haemolysed sample)',
    'Icteric': 'high concentration of bilirubin (Icteric sample)',
    'Insufficient': 'insufficient sample being received',
    'Lab Error': 'a lab mistake',
    'Leaked': 'sample being leaked',
    'Lid Swap': 'sample being contaminated',
    'Lipaemic': 'high concentration of lipids (Lipaemic sample)',
    'Lost in post': 'sample not being received',
    'Mislabelled': 'sample tube not labelled correctly',
    'Mismatch': 'sample tube not labelled correctly',
    'Negative': 'being not detected',
    'No sample': 'sample not being received',
    'Not tested': 'sample not being tested - can be due to failed markers',
    'To follow': 'processing of results not yet being completed',
    'Too Old': 'sample being too old to test',
    'Trig too high': 'Triglycerides value being over  the reporting limit',
    'Unknown': 'test being unknown or sender being unknown',
    'Unlabelled': 'sample tube not being labelled correctly',
    'ND': 'test not being done'
};
