export enum AgeTypes {
    betweenEighteenAndTwenty = 1,
    betweenTwentyAndThirtyNine = 2,
    betweenTwentyAndFifty = 3,
    betweenFourtyAndFiftyNine = 4,
    beforeFourtyFive = 5,
    afterFourtyFive = 6,
    beforeFifty = 7,
    afterFifty = 8,
    afterSixty = 9,
    betweenEighteenAndFiftyNine = 10,
    betweenSixtyAndSixtyNine = 11,
    betweenSeventyAndSeventyNine = 12,
    afterEighty = 13,
}

export const AgeClientValues = {
    [AgeTypes.betweenEighteenAndTwenty]: '18-20',
    [AgeTypes.betweenTwentyAndThirtyNine]: '20-39',
    [AgeTypes.betweenTwentyAndFifty]: '20-50',
    [AgeTypes.betweenFourtyAndFiftyNine]: '40-59',
    [AgeTypes.beforeFourtyFive]: '<45',
    [AgeTypes.afterFourtyFive]: '>45',
    [AgeTypes.beforeFifty]: '<50',
    [AgeTypes.afterFifty]: '>50',
    [AgeTypes.afterSixty]: '>60',
    [AgeTypes.betweenEighteenAndFiftyNine]: '18-59',
    [AgeTypes.betweenSixtyAndSixtyNine]: '60-69',
    [AgeTypes.betweenSeventyAndSeventyNine]: '70-79',
    [AgeTypes.afterEighty]: '>80',
};
