export enum ContradictionTypes {
    acne = 1,
    rosacea = 2,
    eczema = 3,
    brokenSkin = 4,
    skinInfection = 5,
    pregnancy = 6,
    breastFeeding = 7,
    epilepsy = 8,
    cardiacIssues = 9,
    pacemaker = 10,
    cancerWithingTwoYears = 11,
    thrombosis = 12,
    diabetes = 13,
    recentBotoxOrFillers = 14,
    metalPlatesOrPins = 15,
    heartProblemsOrDiseases = 16,
    kidneyDamage = 17,
    liverDamage = 18,
    haemorrhagicDisease = 19,
    traumaOrBleeding = 20,
    numbOrInsensitiveToHeat = 21,
    pacemakerOrDefibrillator = 22,
    lupusOrPhotosensitivityDisorders = 23,
    acneMedicationsOrPhotosensitizingMedications = 24,
    cataractsOrRetinalDisorders = 25,
}