export const FilterValidationRules = {
    interactionArrayMaxLength: 20,
    interactionTypesMaxCount: 10,
    recommendationArrayMaxLength: 70,
    recommendationTypesMaxCount: 10,
    rangeMaxCharactersCount: 10,
    rangeMinValue: 0,
    summaryMaxLength: 10000,
    summaryMinLength: 1,
    whatIsItMaxLength: 10000,
    whatIsItMinLength: 1,
    whatCanYouDoMaxLength: 10000,
    whatCanYouDoMinLength: 1,
    whatAreTheRisksMaxLength: 10000,
    whatAreTheCausesMaxLength: 10000,
    bulletListMaxLength: 15,
    bulletListContentMaxLength: 200,
    studyLinksMaxCount: 4,
    studyLinkMaxLength: 200,
    studyLinkMinLength: 1,
};
