name: sync up to backend prod codecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'master'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CODECOMMIT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CODECOMMIT }}
          aws-region: eu-west-2

      - name: Github to AWS CodeCommit Sync
        uses: tsgit18/sync-up-to-codecommit-action@v1.0.6
        with:
          repository_name: optimallyme-prod_backend_repo
          aws_region: eu-west-2
